import { List } from './list.model';

export const LISTS: List[] = [
    new List("activites", "crafts", "bla", 1),
    new List("artists", "museums", "bla", 2),
    new List("events", "pop-ups", "bla", 3),
    new List("general", "general", "bla", 4),
    new List("pets", "lost and found", "bla", 5),
    new List("politics", "voting", "bla", 6),
    new List("local news", "what's new", "bla", 7),
    new List("volunteers", "help in your community", "bla", 8),
    new List("platonic", "find companionship", "bla", 9),
    new List("women seeking women", "woman-woman", "bla", 10),
    new List("women seeking men", "woman-man", "bla", 11),
    new List("men seeking men", "men-men", "bla", 12),
    new List("men seeking women", "men-women", "bla", 13),
    new List("casual encounters", "casual", "bla", 14),
    new List("missed connections", "find that person", "bla", 15),
    new List("rants and raves", "complain or boast", "bla", 16),
    new List("misc romance", "misc love", "bla", 17),
    new List("arts", "all things art", "bla", 18),
    new List("history", "all things history", "bla", 19),
    new List("outdoor", "all things outdoor", "bla", 20),
    new List("tax", "all things tax", "bla", 21),
    new List("sports", "all things sports", "bla", 22),
    new List("yoga", "all things yoga", "bla", 23),
    new List("photo", "all things photo", "bla", 24),
    new List("jokes", "all things jokes", "bla", 25),
    new List("diet", "all things diet", "bla", 26),
    new List("apts/housing", "find a place", "bla", 27),
    new List("housing swap", "switch it up", "bla", 28),
    new List("housing wanted", "wanted", "bla", 29),
    new List("office", "find an office space", "bla", 30),
    new List("rooms/shared", "find a room", "bla", 31),
    new List("rooms wanted", "wanted", "bla", 32),
    new List("sublets", "sublet your space", "bla", 33),
    new List("vacation rentals", "vacation", "bla", 34),
    new List("parking/storage", "store it", "bla", 35),
    new List("antiques", "vintage", "bla", 36),
    new List("books", "letting go of tons of books", "bla", 37),
    new List("cars", "selling a car", "bla", 38),
    new List("electronics", "selling a computer", "bla", 39),
    new List("furniture", "couch for sale", "bla", 40),
    new List("household", "firewood for sale", "bla", 41),
    new List("tickets", "Gorillaz tickets", "bla", 42),
    new List("tools", "tools for sale", "bla", 43),
    new List("wanted", "wanted items", "bla", 44),
    new List("automotive", "car maintainance", "bla", 45),
    new List("beauty", "salon services", "bla", 46),
    new List("creative", "creative services", "bla", 47),
    new List("event", "event services", "bla", 48),
    new List("financial", "financial services", "bla", 49),
    new List("legal", "legal services", "bla", 50),
    new List("pet", "pet services", "bla", 51),
    new List("real estate", "real estate services", "bla", 52),
    new List("travel", "travel services", "bla", 53),
    new List("accounting", "accounting jobs", "bla", 54),
    new List("food/bev/hosp", "service industry jobs", "bla", 55),
    new List("medical/health", "medical jobs", "bla", 56),
    new List("tech support", "tech jobs", "bla", 57),
    new List("transport", "transportation jobs", "bla", 58),
    new List("tv/film", "tv/film jobs", "bla", 59),
    new List("web/info design", "web/info jobs", "bla", 60),
    new List("computer", "computer work", "bla", 61),
    new List("creative", "creative work", "bla", 62),
    new List("event", "event work", "bla", 63),
    new List("labor", "labor work", "bla", 64),
    new List("talent", "talent work", "bla", 65),
    new List("writing", "writing work", "bla", 66)
  ];
